#include "cpu.h"
/*
cpu_handlers.c
plasm2
plasm2_emu
(c) Noah Wooten 2023, All Rights Reserved
*/

DeclInstruction(MOV);
DeclInstruction(LDI);
DeclInstruction(JMP);
DeclInstruction(NXC);
DeclInstruction(NXE);
DeclInstruction(NXZ);
DeclInstruction(NXG);
DeclInstruction(NXL);
DeclInstruction(CLL);
DeclInstruction(RET);
DeclInstruction(IMR);
DeclInstruction(ADD);
DeclInstruction(SUB);
DeclInstruction(MUL);
DeclInstruction(DIV);
DeclInstruction(MOD);
DeclInstruction(AND);
DeclInstruction(BOR);
DeclInstruction(XOR);
DeclInstruction(LDW);
DeclInstruction(LDB);
DeclInstruction(STW);
DeclInstruction(STB);
DeclInstruction(PSH);
DeclInstruction(POP);
DeclInstruction(PSR);
DeclInstruction(POR);
DeclInstruction(VME);
DeclInstruction(VMD);
DeclInstruction(VPC);
DeclInstruction(VPD);
DeclInstruction(VSI);
DeclInstruction(VSD);
DeclInstruction(SPS);
DeclInstruction(SPG);
DeclInstruction(DSQ);
DeclInstruction(DSC);
DeclInstruction(DSD);
DeclInstruction(DGD);
DeclInstruction(DRS);
DeclInstruction(DPE);
DeclInstruction(DPD);
DeclInstruction(DGC);
DeclInstruction(INT);
DeclInstruction(HND);
DeclInstruction(IRT);
DeclInstruction(ENI);
DeclInstruction(DSI);
DeclInstruction(SHF);
DeclInstruction(SMH);
DeclInstruction(SIT);
DeclInstruction(CMP);

void(*Instructions[256])(void) = {
	ListInstruction(MOV),
	ListInstruction(LDI),
	ListInstruction(JMP),
	ListInstruction(NXC),
	ListInstruction(NXE),
	ListInstruction(NXZ),
	ListInstruction(NXG),
	ListInstruction(NXL),
	ListInstruction(CLL),
	ListInstruction(RET),
	ListInstruction(IMR),
	ListInstruction(ADD),
	ListInstruction(SUB),
	ListInstruction(MUL),
	ListInstruction(DIV),
	ListInstruction(MOD),
	ListInstruction(AND),
	ListInstruction(BOR),
	ListInstruction(XOR),
	ListInstruction(LDW),
	ListInstruction(LDB),
	ListInstruction(STW),
	ListInstruction(STB),
	ListInstruction(PSH),
	ListInstruction(POP),
	ListInstruction(PSR),
	ListInstruction(POR),
	ListInstruction(VME),
	ListInstruction(VMD),
	ListInstruction(VPC),
	ListInstruction(VPD),
	ListInstruction(VSI),
	ListInstruction(VSD),
	ListInstruction(SPS),
	ListInstruction(SPG),
	ListInstruction(DSQ),
	ListInstruction(DSC),
	ListInstruction(DSD),
	ListInstruction(DGD),
	ListInstruction(DRS),
	ListInstruction(DPE),
	ListInstruction(DPD),
	ListInstruction(DGC),
	ListInstruction(INT),
	ListInstruction(HND),
	ListInstruction(IRT),
	ListInstruction(ENI),
	ListInstruction(DSI),
	ListInstruction(SHF),
	ListInstruction(SMH),
	ListInstruction(SIT),
	ListInstruction(CMP),
};